Update patch set 2
Patch Set 2:

Theme chooser started crashing on every boot:

java.lang.RuntimeException: Unable to start receiver org.cyanogenmod.theme.chooser2.BootReceiver: java.lang.IllegalArgumentException: Unknown component: org.cyanogenmod.theme.chooser/org.cyanogenmod.theme.chooser2.BootReceiver
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Unknown component: org.cyanogenmod.theme.chooser/org.cyanogenmod.theme.chooser2.BootReceiver
	at android.os.Parcel.readException(Parcel.java:1624)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:4115)
	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:1905)
	at org.cyanogenmod.theme.chooser2.BootReceiver.onReceive(SourceFile:51)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2759)
	... 8 more


Jira ticket: https://jira.cyanogenmod.org/browse/NIGHTLIES-3335 please look at it

Patch-set: 2
Reviewer: Michał M <12150@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0